#! /bin/sh

set -e

cd "$(dirname "$0")/.."

echo "=> Stopping listener...\n"
sudo update-rc.d oled_mpd.sh remove
sudo /etc/init.d/oled_mpd.sh stop

echo "=> Removing listener...\n"
sudo rm -rf /usr/local/bin/oled_mpd.py 
sudo rm -rf /usr/local/bin/oled_mpd_btn.py 
sudo rm -rf /etc/init.d/oled_mpd.sh 

echo "listener uninstalled.\n"
